#!/usr/bin/env bash
# Quick start guide for the Pico sensor integration

echo "=== Pico Sensor Integration Quick Start ==="
echo ""
echo "1. INSTALL DEPENDENCIES"
echo "   cd backend"
echo "   npm install"
echo ""
echo "2. RUN WITH HARDWARE (Pico connected)"
echo "   npm run dev"
echo ""
echo "   When you see '[Server] Backend listening on http://localhost:5174'"
echo "   the serial reader is ready to receive from Pico 3."
echo ""
echo "3. RUN WITH MOCK DATA (no hardware needed)"
echo "   MOCK_MODE=true npm run dev"
echo ""
echo "   This generates random sensor values (good for testing frontend)"
echo ""
echo "4. TEST THE CONNECTION"
echo "   In another terminal:"
echo "   curl http://localhost:5174/api/sensors"
echo ""
echo "5. VIEW RAW CODES (debugging)"
echo "   curl http://localhost:5174/api/sensors/raw"
echo ""
echo "ENVIRONMENT VARIABLES"
echo "  SERIAL_PORT       Device path (default: COM3; on Linux try /dev/ttyUSB0)"
echo "  BAUD_RATE         Serial speed (default: 115200)"
echo "  MOCK_MODE=true    Generate fake data instead of reading serial"
echo "  DEBUG_MODE=true   Log every decoded code"
echo ""
echo "EXAMPLE: Connect to different Pico"
echo "  SERIAL_PORT=COM5 npm run dev"
echo ""
echo "EXAMPLE: Verbose debugging"
echo "  DEBUG_MODE=true npm run dev"
